### PR TITLE
Added an example of using the Eff monad

### PR DESCRIPTION
**Pull request by etorreborre**
comparing it with a "classical" Free monad and object algebras.

There should probably be a better discussion of the relative merits of Free vs Eff but I don't have time for this :-).

### CODE REVIEW

**Comment by jserranohidalgo** [comment]
@etorreborre Thanks, Eric. We'll rename the `objectalgebras-vs-free-vs-eff` directory to simply `effects` in a future commit, and invite people to contribute with other approaches. For instance, I'm thinking of Pascal Voitot, and his [freek](https://github.com/mandubian/freek) project. Any other else approach you may think of?

Thanks again :)

**Comment by jserranohidalgo** [comment]
@etorreborre We'll also fix the missing `build.properties` file, and the incompatibilities with the `scalaz-core` version, BTW.

**Comment by etorreborre** [comment]
Having @mandubian's Freek version would be good as well indeed.

**Comment by mandubian** [comment]
If you need something from me, you'll tell me and I'll see if I can help ;)

**Comment by jserranohidalgo** [comment]
@mandubian Sure, Pascal! Thanks for volunteering :). The idea is simply having different versions of a simple effectful program, using alternative techniques. In this other [repo](https://github.com/hablapps/bypassingfreemonads), you will find two versions of one example of such a simple program doing Input/Output and Logging, and two implementations: one using [object algebras](https://github.com/hablapps/bypassingfreemonads/blob/functionalkats/src/test/scala/objectalgebras.scala) and another one using [free monads](https://github.com/hablapps/bypassingfreemonads/blob/functionalkats/src/test/scala/freemonads.scala) (similar versions using these techniques can also be found in this repo as well, but they will be replaced eventually with those ones). Eric just added in this repo a [third version](https://github.com/hablapps/gist/blob/master/src/test/scala/objectalgebras-vs-free-vs-eff/Eff.scala) of those programs using the Eff monad, and it would be great if you could also add a fourth one using Freek. Your version might be simply added into the same directory, after renaming its name from `objectalgebra-vs-free-vs-eff` to `effects`. There is also a README file in that directory, which aims at describing the similarities and differences between the different implementations. If you like it the idea, please, feel free to add anything you like there as well. Thanks!

**Pull request merged**
